### ISSUE TITLE
this token logs you lmao

### ISSUE THREAD

**Issue by TheProDudeXD** [C0MPL3XB/Discord-Token-Generator#3]
imagine being so retarded to believe token generators :skull:
![image](https://user-images.githubusercontent.com/99324685/154020735-c6edc56f-e711-42ec-93fd-89b1b7cd7a81.png)

**Comment by onlydrip** [comment]
just look through the code you idiot

**Comment by MaiKokain** [comment]
> [just look through the code you idiot](https://github.com/C0MPL3XB/Discord-Token-Generator/issues/3#issuecomment-1040000291)

just did. fishy with [install.bat](https://github.com/C0MPL3XB/Discord-Token-Generator/blob/main/install.bat). Why tf start it in some sus obfuscated python file ([main/util/main.pyw](https://github.com/C0MPL3XB/Discord-Token-Generator/blob/main/main/util/main.pyw)) rather than [generator.py](https://github.com/C0MPL3XB/Discord-Token-Generator/blob/main/Generator.py) and why would someone make a file obfuscated and not the other files. if its so private why don't git ignore it.

**Comment by MaiKokain** [comment]
bro fr deleted the comment

**Comment by MaiKokain** [comment]
that's gay ngl
